version: "3.8"

services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev

    volumes:
      - /app/node_modules
      - ./server:/app
    
    ports:
      - "3002:3002"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
  
   # to fix the issue of EACCESS
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
    ports:
      - "3000:3000"
  
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"